spring:
  application:
    name: mall-monitor
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 8101
