package com.example.mallmbg.model;

import java.io.Serializable;

public class UmsRolePermissionRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_role_permission_relation.id
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_role_permission_relation.role_id
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_role_permission_relation.permission_id
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_role_permission_relation
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_role_permission_relation.id
     *
     * @return the value of ums_role_permission_relation.id
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_role_permission_relation.id
     *
     * @param id the value for ums_role_permission_relation.id
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_role_permission_relation.role_id
     *
     * @return the value of ums_role_permission_relation.role_id
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_role_permission_relation.role_id
     *
     * @param roleId the value for ums_role_permission_relation.role_id
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_role_permission_relation.permission_id
     *
     * @return the value of ums_role_permission_relation.permission_id
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_role_permission_relation.permission_id
     *
     * @param permissionId the value for ums_role_permission_relation.permission_id
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role_permission_relation
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}