package com.example.mallmbg.mapper;

import com.example.mallmbg.model.CmsTopicComment;
import com.example.mallmbg.model.CmsTopicCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsTopicCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    long countByExample(CmsTopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    int deleteByExample(CmsTopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    int insert(CmsTopicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    int insertSelective(CmsTopicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    List<CmsTopicComment> selectByExample(CmsTopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    CmsTopicComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    int updateByExampleSelective(@Param("record") CmsTopicComment record, @Param("example") CmsTopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    int updateByExample(@Param("record") CmsTopicComment record, @Param("example") CmsTopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    int updateByPrimaryKeySelective(CmsTopicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Wed Feb 23 16:48:48 CST 2022
     */
    int updateByPrimaryKey(CmsTopicComment record);
}